receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  # tracescleaner:
  #   otel:
  #     protocols:
  #       http:
  #         endpoint: 0.0.0.0:14318
  #   exclude:
  #     - lets

processors:
  batch:
  tracescleaner:
    exclude:
      - lets

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: localhost:14317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tracescleaner, batch]
      exporters: [otlp/jaeger, debug]
  telemetry:
    logs:
      level: debug
