version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - otel-collector
    links:
      - temperature
      - storage
      - db
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - POSTGRES_HOST=db
      - TEMPERATURE_HOST=temperature
      - STORAGE_HOST=storage

  temperature:
    build: ./temperature
    ports:
      - "8080:8080"
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=eu01xxb126e8179b3753fafe692f1814FFFFNRAL
      - OTEL_SERVICE_NAME=temperature
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - DB_NAME=temperature_db
    depends_on:
      - db
      - otel-collector
    links:
      - db

  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: temperature_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  storage:
    build: ./storage
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - otel-collector
      - minio
    links:
      - minio

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=weather-data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    ports:
      - "3030:3000"

  jaeger:
    image: jaegertracing/all-in-one:1.32.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889" # Prometheus metrics exporter port

volumes:
  postgres_data:
  grafana-data:
  minio_data:

