receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 50
    spike_limit_percentage: 30

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/nr:
    endpoint: https://otlp.eu01.nr-data.net:443
    headers:
      api-key: eu01xxb126e8179b3753fafe692f1814FFFFNRAL
    tls:
      insecure: true
      
service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch, memory_limiter]
      exporters: [otlp, otlp/nr]
